//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars_DealerShip_FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_Table
    {
        public int Car_ID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string Color { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
